apiVersion: v1
kind: Service
metadata:
  name: flask-eks-service
  namespace: flask-eks
  labels:
    app: flask-eks-app
spec:
  type: LoadBalancer
  selector:
    app: flask-eks-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
